.TH progscrape 1 "July 2010"
.SH NAME
progscrape \- \fBXarn\fR's Shiichan webscraper
.SH SYNOPSIS
\fBprogscrape\fR [\fIOPTION\fR]... [\fIDB\fR]
.SH DESCRIPTION
This is a webscraper for Shiichan textboards, originally designed for world4ch's /prog/.
.br
\fBprogscrape\fR determines what to scrape based on Shiichan's subject.txt, and can scrape over either the usual HTML interface or world4ch's JSON interface. The content scraped is placed in an SQLite 3 database (\fBprog.db\fR by default).
.SH OPTIONS
\fB\-\-json\fR
Use the JSON interface, if possible. (default)
.TP
\fB\-\-html\fR, \fB\-\-no-json
Use the HTML interface.
.TP
\fB\-\-verify-trips\fR
When using the JSON interface, drop to the HTML interface to verify if ambiguous tripcodes are legitimate. (default)
.TP
\fB\-\-no\-verify\-trips\fR
When using the JSON interface, do not try to verify ambiguous tripcodes.
.TP
\fB\-\-aborn\fR
When using the JSON interface, keep deleted posts. They will exist in the database with author "SILENT!ABORN", content "SILENT", and timestamp 1234. (default)
.TP
\fB\-\-no\-aborn\fR
When using the JSON interface, ignore deleted posts.
.TP
\fB\-\-no\-html\fR
Equivalent to \fB\-\-json \-\-no\-verify\-trips\fR.
.TP
\fB\-\-progress\-bar\fR
Display an animated progress bar during scraping.
.TP
\fB\-\-no\-progress\-bar\fR
Display the traditional progress report instead. (default)
.TP
\fB\-\-base\-url\fR=\fIURL\fR
Specify base URL of the board to scrape. (default: \fBhttp://dis.4chan.org\fR)
.TP
\fB\-\-port\fR=\fIURL\fR
Specify the port the webserver is running on. (default: \fB80\fR)
.TP
\fB\-\-board\fR=\fIBOARD\fR
Specify board to scrape. (default: \fB/prog/\fR)
.TP
\fB\-\-charset\fR=\fICHARSET\fR
Specify the character encoding the board uses. (default: \fButf-8\fR)
.TP
\fB\-\-partial\fR
Read a list of thread IDs on standard input and only scrape those (provided they're valid IDs and need updating).
.TP
\fB\-\-threads\fR=\fITHREADS\fR
How many scraper threads to use. (default \fB1\fR)
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help message and exit.
.SH "REPORTING BUGS"
Report \fBprogscrape\fR bugs to cairnarvon@gmail.com, or on the Github bugtracker: <http://github.com/Cairnarvon/progscrape/issues>.
.SH COPYRIGHT
Copyright \(co 2008, 2009, 2010 Koen Crolla.
.br
Licensed as free software under the MIT license.
.SH "SEE ALSO"
\fBsqlite3\fR(1)
